using MinuteMind.Models;
using MinuteMind.Services.Contracts;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace MinuteMind.Services.Implementations;

public class PdfExportService : IPdfExportService
{
    public Task<string> ExportAsync(Meeting meeting)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        var minutes = string.IsNullOrEmpty(meeting.MinutesJson)
            ? new MeetingMinutes()
            : System.Text.Json.JsonSerializer.Deserialize<MeetingMinutes>(meeting.MinutesJson) ?? new MeetingMinutes();

        var path = Path.Combine(FileSystem.AppDataDirectory,
            $"{meeting.Title.Replace(" ", "_")}_{DateTime.Now:yyyyMMdd}.pdf");

        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Element(header =>
                {
                    header.Column(col =>
                    {
                        col.Item().Text(meeting.Title)
                            .FontSize(24).Bold().FontColor("#005FAA");
                        col.Item().Text($"{meeting.CreatedAt:MMMM dd, yyyy} • {meeting.Duration:mm\\:ss} duration")
                            .FontSize(11).FontColor("#666666");
                        col.Item().PaddingTop(8).LineHorizontal(1).LineColor("#E3E2E1");
                    });
                });

                page.Content().PaddingTop(16).Column(col =>
                {
                    // Attendees
                    if (minutes.Attendees.Count > 0)
                    {
                        col.Item().Text("Attendees").FontSize(14).Bold().FontColor("#005FAA");
                        col.Item().PaddingTop(4).PaddingBottom(12).Text(
                            string.Join(", ", minutes.Attendees)).FontColor("#404752");
                    }

                    // Discussion Points
                    if (minutes.DiscussionPoints.Count > 0)
                    {
                        col.Item().Text("Key Discussion Points").FontSize(14).Bold().FontColor("#005FAA");
                        col.Item().PaddingTop(4).PaddingBottom(12).Column(list =>
                        {
                            foreach (var point in minutes.DiscussionPoints)
                                list.Item().Text($"• {point}").FontColor("#404752");
                        });
                    }

                    // Decisions
                    if (minutes.Decisions.Count > 0)
                    {
                        col.Item().Text("Decisions").FontSize(14).Bold().FontColor("#005FAA");
                        col.Item().PaddingTop(4).PaddingBottom(12).Column(list =>
                        {
                            foreach (var d in minutes.Decisions)
                                list.Item().Text($"• [{d.Category}] {d.Text}").FontColor("#404752");
                        });
                    }

                    // Action Items
                    if (minutes.ActionItems.Count > 0)
                    {
                        col.Item().Text("Action Items").FontSize(14).Bold().FontColor("#005FAA");
                        col.Item().PaddingTop(4).Column(list =>
                        {
                            foreach (var a in minutes.ActionItems)
                            {
                                var status = a.IsCompleted ? "✓" : "○";
                                list.Item().Text($"{status} {a.Description} — {a.Assignee} (due {a.DueDate})")
                                    .FontColor(a.IsCompleted ? "#666666" : "#1A1C1C");
                            }
                        });
                    }
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by MinuteMind • ").FontColor("#999999").FontSize(9);
                    text.Span($"{DateTime.Now:MMM dd, yyyy}").FontColor("#999999").FontSize(9);
                });
            });
        }).GeneratePdf(path);

        return Task.FromResult(path);
    }
}
